<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="WalletHubDemo" duration-ms="44472" started-at="2016-12-26T04:31:49Z" finished-at="2016-12-26T04:32:33Z">
    <groups>
    </groups>
    <test name="FacebookMessage" duration-ms="14065" started-at="2016-12-26T04:31:49Z" finished-at="2016-12-26T04:32:03Z">
      <class name="facebookmessage.suites.FacebookMessage">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:facebookmessage.suites.FacebookMessage@100fc185]" name="beforeTest" is-config="true" duration-ms="2815" started-at="2016-12-26T11:31:49Z" finished-at="2016-12-26T11:31:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="postAFacebookMessage()[pri:0, instance:facebookmessage.suites.FacebookMessage@100fc185]" name="postAFacebookMessage" duration-ms="11129" started-at="2016-12-26T11:31:51Z" finished-at="2016-12-26T11:32:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postAFacebookMessage -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:facebookmessage.suites.FacebookMessage@100fc185]" name="afterTest" is-config="true" duration-ms="109" started-at="2016-12-26T11:32:03Z" finished-at="2016-12-26T11:32:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- facebookmessage.suites.FacebookMessage -->
    </test> <!-- FacebookMessage -->
    <test name="WalletHubReview" duration-ms="30384" started-at="2016-12-26T04:32:03Z" finished-at="2016-12-26T04:32:33Z">
      <class name="wallethub.suites.WalletHubReview">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:wallethub.suites.WalletHubReview@1593948d]" name="beforeTest" is-config="true" duration-ms="9652" started-at="2016-12-26T11:32:03Z" finished-at="2016-12-26T11:32:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="WalletHubReviewVerify()[pri:0, instance:wallethub.suites.WalletHubReview@1593948d]" name="WalletHubReviewVerify" duration-ms="20121" started-at="2016-12-26T11:32:12Z" finished-at="2016-12-26T11:32:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at wallethub.resources.ProfileScreen.verifyActivity(ProfileScreen.java:71)
	at wallethub.suites.WalletHubReview.WalletHubReviewVerify(WalletHubReview.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WalletHubReviewVerify -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:wallethub.suites.WalletHubReview@1593948d]" name="afterTest" is-config="true" duration-ms="607" started-at="2016-12-26T11:32:32Z" finished-at="2016-12-26T11:32:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- wallethub.suites.WalletHubReview -->
    </test> <!-- WalletHubReview -->
  </suite> <!-- WalletHubDemo -->
</testng-results>
